version: 2

build:
  image: stable

python:
  system_packages: true
  install:
    - method: pip
      path: .
      extra_requirements:
         - doc
         - plotting
         - bloch_sphere_visualization
         - fancy_progressbar
