dist: xenial

language: python

python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels conda-forge
  - conda info -a
  - conda env create -f ./environment.yml
  - source activate filter_functions
  - pip install .[fancy_progressbar,doc,tests]

script:
  - coverage run --rcfile=coverage.ini -m pytest

after_success:
  - coveralls

notifications:
  email: false

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  edge: true                            # use travis deployment v2
  on:
    tags: true                          # only deploy tagged commits
  skip_existing: true                   # upload artifacts only once
  username: "__token__"
  password:
    secure: "QqP7Yuz2aecCEOznFzKduI9rZfV87HODvsJEdiiM43Zbu7sfCp5HeSEhBTU8DD2d4Tcy1PnaLMCSIXjAw4IPDTU7tIVDQ8W2lgj6IY5ti9CnjK1+3LDHSNSbq5+WfGzViS2VAzY40S27P1sJKTgGU5jShLPpRT6YgPSSmIVfYdLOeQ3XYrZyLy3qj6tf8LC4URSLswZ7vPKvufzuZJPcHuWekuhK+IFrOutQ4RfzvBu4y4GGYj/8OgaxpWHfB9tvZU2h9dlRtMERG2CbS2chjDi84z0VT6cKwbJYJJcGLwyGF/UL7MrIyN8/7sw5dUXFfRjE3ENOskHJw+5em3fedcNir4Y94JPBbDzwexLb+MNByto7B4lcvFqo2Hzh4kQ/6G7IroIayXjC8HyKN2JAWwBuO7sKXpCvxOVaK/2FEIrpUyvKYHK598Pvx7d+2IEPWZml5baoUB3ENjGM+fg6tWjI3dR40KMmwtul7cL4wv8JGPMlFqXy8IBRBxIEmU5/CKxzDQ5dni0HboMspQcBi17pSYet6YGyWyI4TyvoyvgGbOiAd5e6CU/mabyAb+Fue17QPczsHkXq110MeuqNLLKxsPqqqUY8Wg3xHkaV9GzXH+KEbCeYZJA9MGry9W9m7ZFTvCVwXahsLyEYshDG7KQyZitq6RL7SKU0/LW22U4="
